#define N_POPULACAO 1000
#define N_DESCENDENTES_DESCARTE 100
#define N_GERACOES_EVOLUIR 100
#define TAXA_MUTACAO 0.9

#include "ag.h"

int main() {
	executar(N_POPULACAO,N_DESCENDENTES_DESCARTE, N_GERACOES_EVOLUIR,TAXA_MUTACAO);
}